
# All paths relative to this config file

generators:
  generator_c:
    enabled: true
    paths:
      output_enums: ./firmware/src/tm_enums.h
      output_header: ./firmware/src/can/can_endpoints.h
      output_impl: ./firmware/src/can/can_endpoints.c
      output_metadata_header: ./firmware/src/can/avlos_endpoint_metadata.h
      output_metadata_impl: ./firmware/src/can/avlos_endpoint_metadata.c
    header_includes:
    - src/common.h
    - src/tm_enums.h
    impl_includes:
    - <string.h>
    - src/adc/adc.h
    - src/system/system.h
    - src/sensor/sensors.h
    - src/observer/observer.h
    - src/motor/motor.h
    - src/scheduler/scheduler.h
    - src/controller/controller.h
    - src/nvm/nvm.h
    - src/watchdog/watchdog.h
    - src/can/can_endpoints.h
  generator_rst:
    enabled: true
    paths:
      output_file: ./docs/protocol/reference.rst

